### ISSUE TITLE
MacOS

### ISSUE THREAD

**Issue by esteMesa** [baigouy/EPySeg#2]
Hi, 
Thank you for sharing your software. I am trying to download the package on a MacOS system but I, too, am receiving an error regarding tensorflow:   

"ERROR: Could not find a version that satisfies the requirement tensorflow-gpu>=2.0.0 (from epyseg) (from versions: none)
ERROR: No matching distribution found for tensorflow-gpu>=2.0.0 (from epyseg)"

I was looking at the setup.py file, I am not sure if lines 41 and 42 are requiring for both to be met as opposed to gpu or non-gpu. Any ideas on how to get around this? 

Appreciate your feedback.

**Comment by baigouy** [comment]
Hi,

I don't exactly know what the problem is. It could have something to do with the python version you are using or could be that your pip/wheel is not up to date. I need more infos to help you:

-Which version of python are you using, and are you using anaconda or regular python ?
-can you run the following command (if you are using regular python) and then try epyseg install again:
pip install --upgrade pip

You are most likely right for the pb with lines 41 and 42 of the setup.py file, but I have to say that I sometimes get the system to default to CPU even when a GPU is available when I only install tensorflow without also installing tensorflow-gpu (especially with anaconda), it's most likely an error in my system configuration somewhere and it's not clear to me why it solves things but it really does so. But you are right, trying to install tensorflow-gpu on mac will be a pb on recent mac computers (since there is no GPU support for recent Macs and recent Mac oses even when they have the appropriate GPU). So from now on (as of version 0.1.11) tensorflow-GPU will not be installed on MacOS (I have edited the setup.py file), thanks for your help and let me know if that solves things for you.

best

ps: in the meantime and in any case you can also try the colab versions that will always work (see below)

https://github.com/baigouy/notebooks/blob/master/Epyseg_build_and_train.ipynb
https://github.com/baigouy/notebooks/blob/master/Epyseg_segment.ipynb

**Comment by baigouy** [comment]
I guess that should fix things up, please feel free to reopen if that is not the case.
