### ISSUE TITLE
EPySeg failed to load. Please repeat this step.

### ISSUE THREAD

**Issue by tzerhan** [baigouy/EPySeg#7]
<img width="936" alt="image" src="https://user-images.githubusercontent.com/1099445/224785892-d262eef0-d4cf-4a12-adea-1c4933ed328d.png">

Any help is much appreciated! This is run on google colab.

**Comment by baigouy** [comment]
dear @tzerhan, 

colab has changed its default python version from 3.7 to 3.9, which creates an issue because there is no version of epyseg for python 3.9. I have pushed an update of EPySeg to testpy, I made quite some changes and I'm not ready yet for update to real pypi. However changing the last two lines of the code should fix the issue for you:

```
!pip install scikit-learn>=1.0.2 #before it was !pip install sklearn
!pip install --no-deps -i https://test.pypi.org/simple/ epyseg==0.1.30 #before it was pip install --no-deps epyseg
```

thanks for the bug report, hope this will fix the issue, let me know otherwise

PS: hopefully I'll push a real update/fix by the end of the month when I have more time

**Comment by baigouy** [comment]
I have pushed an up to date version of the tool to pypi, that should fix the problem you mentioned.
